// Generated by CoffeeScript 1.6.2
(function() {
  var LocalStrategy, User, passport, restrict;

  passport = require("passport");

  LocalStrategy = require("passport-local").Strategy;

  User = require('./model').User;

  passport.use(new LocalStrategy({
    usernameField: '_id',
    passwordField: 'password'
  }, function(username, password, done) {
    return User.findById(username, function(err, user) {
      if (err != null) {
        return done(err);
      } else if (user == null) {
        return done(null, false, "User doesn't exist");
      } else if (user.password !== password) {
        return done(null, false, "The password doesn't match the username");
      } else {
        return done(null, user, {
          scope: 'all'
        });
      }
    });
  }));

  passport.serializeUser(function(user, done) {
    return done(null, user._id);
  });

  passport.deserializeUser(function(id, done) {
    return User.findById(id, function(err, user) {
      return done(null, user);
    });
  });

  restrict = function(request, topic, permission) {
    if (!request.isAuthenticated()) {
      return false;
    } else {
      return console.log("ser", request.user);
    }
  };

  module.exports = {
    canWrite: function(request, topic) {
      return restrict(request, topic, 'w');
    },
    canRead: function(request, topic) {
      return restrict(request, topic, 'r');
    }
  };

}).call(this);
