// Generated by CoffeeScript 1.6.2
(function() {
  var app, express, port, server, users;

  express = require('express');

  app = express();

  port = 3333;

  server = app.listen(port, function() {
    return console.log("Express server listening on port %d in %s mode", server.address().port, app.settings.env);
  });

  app.configure(function() {
    app.set('port', port);
    app.use(express.bodyParser());
    app.use(express.methodOverride());
    return app.use(express.compress());
  });

  app.configure('development', function() {
    return app.use(express.errorHandler());
  });

  app.all('/server-check', function(request, response) {
    return response.send("Cloud running");
  });

  users = [
    {
      id: "michal",
      name: "Michal Srb",
      year: 2011,
      uri: "/users/michal"
    }, {
      id: "pamela",
      name: "Cruz",
      year: 2011,
      uri: "/users/pamela"
    }
  ];

  app.get('/users', function(request, response) {
    return response.send(users);
  });

  app.get('/users/:name', function(request, response) {
    var user, _i, _len, _results;

    _results = [];
    for (_i = 0, _len = users.length; _i < _len; _i++) {
      user = users[_i];
      if (user.id === request.params.name) {
        response.send(user);
        break;
      } else {
        _results.push(void 0);
      }
    }
    return _results;
  });

  app.put('/client/create-form', function(request, response) {
    res.writeHead(200, {
      'Content-Type': 'text/plain'
    });
    return res.end(JSON.stringify(list));
  });

}).call(this);
