// Generated by CoffeeScript 1.6.2
(function() {
  module.exports = function(Q) {
    Q.makePromise.prototype.thenEach = function(callback) {
      return this.then(function(values) {
        var value, _i, _len, _results;

        _results = [];
        for (_i = 0, _len = values.length; _i < _len; _i++) {
          value = values[_i];
          _results.push(callback(value));
        }
        return _results;
      });
    };
    return Q.map = function(values, callback) {
      var k, v;

      if (Array.isArray(values)) {
        return Q.all(values.map(callback));
      } else {
        return Q.all((function() {
          var _results;

          _results = [];
          for (k in values) {
            v = values[k];
            _results.push(callback(v, k));
          }
          return _results;
        })());
      }
    };
  };

}).call(this);
