// Generated by CoffeeScript 1.6.2
(function() {
  var Course, User, _ref;

  _ref = require('./model'), Course = _ref.Course, User = _ref.User;

  module.exports = function(app) {
    app.get('/users', function(request, response) {
      return response.send(users);
    });
    return app.get('/users/:name', function(request, response) {
      return User.find({
        name: request.params.name
      }, function(err, docs) {
        return response.send(docs);
      });
    });
  };

}).call(this);
