// Generated by CoffeeScript 1.6.2
(function() {
  var Answer, CommentA, CommentQ, Event, File, Q, Question, Topic, User, authenticated, canRead, canWrite, fs, mkdirp, os, passport, path, _ref, _ref1;

  Q = require('q');

  (require('./q-each'))(Q);

  passport = require("passport");

  _ref = require('./model'), Topic = _ref.Topic, User = _ref.User, File = _ref.File, CommentA = _ref.CommentA, CommentQ = _ref.CommentQ, Question = _ref.Question, Answer = _ref.Answer, Event = _ref.Event;

  _ref1 = require('./authentication'), canRead = _ref1.canRead, canWrite = _ref1.canWrite, authenticated = _ref1.authenticated;

  path = require('path');

  fs = require('fs');

  os = require('os');

  mkdirp = Q.denodeify(require('mkdirp'));

  module.exports = function(app) {
    var addEvent, batchUserData, findAnswer, findCommentA, findCommentQ, findFile, findQuestion, findTopic, fromArrayToMap, getAnswer, getEvents, getOwners, getTopic, objectify, populateOwner, usersFiles;

    app.get('/users/:username', authenticated, function(request, response) {
      return usersFiles(request.params.username).then(function(user) {
        return response.send(user);
      }, function(error) {
        return response.send(error);
      });
    });
    usersFiles = function(userId) {
      return Q.ninvoke(User, 'findById', userId).then(function(user) {
        return Q.ninvoke(user, 'populate', 'topics.code');
      }).then(function(user) {
        var fileLists, topicPermissions;

        user = user.toObject();
        topicPermissions = user.topics;
        fileLists = Q.map(topicPermissions, function(_arg) {
          var code, topicId;

          code = _arg.code;
          topicId = code._id;
          return Q.ninvoke(File, 'find', {
            topicCode: topicId
          });
        });
        return fileLists.thenEach(function(files, i) {
          return user.topics[i].code.files = files;
        }).then(function() {
          return user;
        });
      });
    };
    app.get('/files/:topicId/:fileName', authenticated, function(request, response) {
      var fileName, topicId, _ref2;

      _ref2 = request.params, topicId = _ref2.topicId, fileName = _ref2.fileName;
      return response.sendFile(path.join(__dirname, "files/" + topicId + "/" + fileName), function(err) {
        return response.send(404, "File not found");
      });
    });
    app.post('/users', function(request, response) {
      var user;

      user = new User({
        name: request.body.name,
        _id: request.body._id,
        password: request.body.password,
        email: request.body.email,
        facebook: request.body.facebook,
        topics: request.body.topics
      });
      return user.save(function(err) {
        if (err != null) {
          return response.send(err);
        } else {
          return response.send(user);
        }
      });
    });
    fromArrayToMap = function(idKey, array) {
      var element, result, _i, _len;

      result = {};
      for (_i = 0, _len = array.length; _i < _len; _i++) {
        element = array[_i];
        result[element[idKey]] = element;
      }
      return result;
    };
    objectify = function(topic) {
      var answer, file, question, _i, _j, _k, _len, _len1, _len2, _ref2, _ref3, _ref4;

      _ref2 = topic.files;
      for (_i = 0, _len = _ref2.length; _i < _len; _i++) {
        file = _ref2[_i];
        _ref3 = file.questions;
        for (_j = 0, _len1 = _ref3.length; _j < _len1; _j++) {
          question = _ref3[_j];
          _ref4 = question.answers;
          for (_k = 0, _len2 = _ref4.length; _k < _len2; _k++) {
            answer = _ref4[_k];
            answer.comments = fromArrayToMap('_id', answer.comments);
          }
          question.comments = fromArrayToMap('_id', question.comments);
          question.answers = fromArrayToMap('_id', question.answers);
        }
        file.questions = fromArrayToMap('_id', file.questions);
      }
      topic.files = fromArrayToMap('_id', topic.files);
      return topic;
    };
    getOwners = function(user) {
      var fileOwners;

      return fileOwners = Q.map(user.topics, function(_arg) {
        var code;

        code = _arg.code;
        return Q.all([
          Q.ninvoke(File, 'populate', code.files, {
            path: 'owner',
            select: '_id name'
          }), Q.map(code.files, function(file) {
            return Q.all([
              Q.ninvoke(Question, 'populate', file.questions, {
                path: 'owner',
                select: '_id name'
              }), Q.map(file.questions, function(question) {
                return Q.all([
                  Q.ninvoke(CommentQ, 'populate', question.comments, {
                    path: 'owner',
                    select: '_id name'
                  }), Q.ninvoke(Answer, 'populate', question.answers, {
                    path: 'owner',
                    select: '_id name'
                  }), Q.map(question.answers, function(answer) {
                    return Q.ninvoke(CommentA, 'populate', answer.comments, {
                      path: 'owner',
                      select: '_id name'
                    });
                  })
                ]);
              })
            ]);
          })
        ]);
      });
    };
    batchUserData = function(request, response) {
      var topicCodes;

      topicCodes = request.user.topics;
      return Q.ninvoke(request.user, 'populate', 'topics.code').then(function(user) {
        return getOwners(user).then(function() {
          return user;
        });
      }).then(function(user) {
        var code, permission, topics, _i, _len, _ref2, _ref3;

        user = user.toObject();
        topics = {};
        _ref2 = user.topics;
        for (_i = 0, _len = _ref2.length; _i < _len; _i++) {
          _ref3 = _ref2[_i], code = _ref3.code, permission = _ref3.permission;
          code.permission = permission;
          topics[code._id] = objectify(code);
        }
        user.topics = topics;
        return getEvents(topicCodes).then(function(events) {
          user.events = events;
          return response.send(user);
        }, function(error) {
          return response.send(error);
        }).done();
      }).done();
    };
    app.post('/login', passport.authenticate('local'), function(request, response) {
      return batchUserData(request, response);
    });
    app.get('/data', authenticated, function(request, response) {
      return batchUserData(request, response);
    });
    app.post('/users/:username', authenticated, function(request, response) {
      if (request.user._id !== request.params.username) {
        return response.send(401, "User doesn't have permissions");
      }
      return User.update(request.user, {
        name: request.body.name,
        password: request.body.password,
        email: request.body.email,
        facebook: request.body.facebook
      }, function(err, numberAffected, res) {
        if (err != null) {
          return response.send(err);
        } else {
          return response.send(request.user);
        }
      });
    });
    app.post('/topics', function(request, response) {
      var topic;

      topic = new Topic({
        name: request.body.name,
        _id: request.body._id,
        files: [],
        types: request.body.types
      });
      return topic.save(function(err) {
        if (err != null) {
          return response.send(err);
        } else {
          return response.send(topic);
        }
      });
    });
    app.get('/topics/:code', authenticated, function(request, response) {
      return getTopic(request.params.code).then(function(topic) {
        topic = topic.toObject();
        topic.permission = (function() {
          var code, permission, _i, _len, _ref2, _ref3;

          _ref2 = request.user.topics;
          for (_i = 0, _len = _ref2.length; _i < _len; _i++) {
            _ref3 = _ref2[_i], code = _ref3.code, permission = _ref3.permission;
            if (code === topic._id) {
              return permission;
            }
          }
        })();
        return response.send(topic);
      }, function(error) {
        return response.send(error);
      });
    });
    getTopic = function(topicId) {
      return Q.ninvoke(Topic, 'findById', topicId).then(function(topic) {
        return topic;
      });
    };
    addEvent = function(type, model, url, topicCode) {
      var event;

      event = new Event({
        model: model,
        type: type,
        topicCode: topicCode,
        url: url
      });
      return event.save(function(err) {
        if (err != null) {
          return err;
        } else {
          return event;
        }
      });
    };
    app.get('/events', authenticated, function(request, response) {
      return getEvents(request.user.topics).then(function(events) {
        return response.send(events);
      }, function(error) {
        return response.send(error);
      });
    });
    getEvents = function(topics) {
      var code, topicCodes;

      topicCodes = (function() {
        var _i, _len, _results;

        _results = [];
        for (_i = 0, _len = topics.length; _i < _len; _i++) {
          code = topics[_i].code;
          _results.push(code);
        }
        return _results;
      })();
      return Q.ninvoke(Event.find({}).where('topicCode')["in"](topicCodes).select('timestamp').select('url').select('type').sort('-timestamp'), 'exec');
    };
    findTopic = function(_arg) {
      var topicId;

      topicId = _arg.topicId;
      return Q.ninvoke(Topic, 'findById', topicId).then(function(topic) {
        if (topic == null) {
          throw [404, "topic not found " + topicId];
        }
        return topic;
      });
    };
    app.get('/topics/:topicId/files', authenticated, function(request, response) {
      return findTopic(request.params).then(function(topic) {
        return response.send(topic.files);
      }, function(error) {
        return response.send(error);
      }).done();
    });
    app.post('/topics/:topicId/upload', authenticated, function(request, response) {
      return response.send((function() {
        var file, files, _i, _len, _results;

        files = Array.isArray(request.files.form.files[0]) ? request.files.form.files[0] : request.files.form.files;
        _results = [];
        for (_i = 0, _len = files.length; _i < _len; _i++) {
          file = files[_i];
          _results.push({
            tmpName: path.basename(file.path)
          });
        }
        return _results;
      })());
    });
    app.post('/topics/:topicId/files', authenticated, function(request, response) {
      var file, filePath, fileSaved, topicDir;

      if (!canWrite(request, request.params.topicId)) {
        return response.send(401, 'User doesnt have write permission');
      }
      topicDir = path.join(__dirname, "files/" + request.params.topicId);
      filePath = path.join(topicDir, request.body.name);
      fileSaved = mkdirp(topicDir).then(function() {
        console.log(path.join(app.get('uploadDir'), request.body.tmpName));
        console.log(fs.statSync(path.join(app.get('uploadDir'), request.body.tmpName)));
        return console.log(fs.renameSync(path.join(app.get('uploadDir'), request.body.tmpName), filePath));
      });
      file = new File({
        _id: request.body._id,
        path: filePath,
        name: request.body.name,
        owner: request.body.owner,
        type: request.body.type,
        date: request.body.date
      });
      return findTopic(request.params).then(function(topic) {
        topic.files.addToSet(file);
        addEvent("Added", "File", "topics/" + request.params.topicId + "/files/" + file._id, request.params.topicId);
        return Q.ninvoke(topic, 'save').then(function() {
          return response.send(file);
        }, function(error) {
          throw error;
          return response.send(500, error);
        }).done();
      }).done();
    });
    findFile = function(request, _arg) {
      var fileId, topicId;

      topicId = _arg.topicId, fileId = _arg.fileId;
      return findTopic({
        topicId: topicId
      }).then(function(topic) {
        if (!canRead(request, topicId)) {
          throw [401, "cant read"];
        }
        return [topic, topic.files.id(fileId)];
      });
    };
    app.get('/topics/:topicId/files/:fileId', authenticated, function(request, response) {
      return findFile(request, request.params).then(function(_arg) {
        var file, topic;

        topic = _arg[0], file = _arg[1];
        return response.send(file);
      }, function(error) {
        return response.send.apply(response, error);
      }).done();
    });
    app["delete"]('/topics/:topicId/files/:fileId', authenticated, function(request, response) {
      return findFile(request, request.params).then(function(_arg) {
        var file, topic;

        topic = _arg[0], file = _arg[1];
        topic.files.pull(file);
        return response.send(topic);
      }, function(error) {
        return response.send.apply(response, error);
      }).done();
    });
    app.post('/topics/:topicId/files/:fileId', authenticated, function(request, response) {
      return findFile(request, request.params).then(function(_arg) {
        var file, topic;

        topic = _arg[0], file = _arg[1];
        file.name = request.body.name;
        file.path = request.body.path;
        file.date = request.body.date;
        return Q.ninvoke(topic, 'save').then(function() {
          addEvent("Modified", "File", "topics/" + request.params.topicId + "/files/" + request.params.fileId, request.params.topicId);
          return response.send(file);
        }, function(error) {
          return response.send(error);
        }).done();
      }).done();
    });
    app.post('/topics/:topicId/files/:fileId/questions', authenticated, function(request, response) {
      var question;

      question = new Question({
        owner: request.body.owner,
        filePosition: request.body.filePosition,
        text: request.body.text,
        createdTime: new Date()
      });
      return findFile(request, request.params).then(function(_arg) {
        var file, topic;

        topic = _arg[0], file = _arg[1];
        file.questions.addToSet(question);
        return Q.ninvoke(topic, 'save');
      }).then(function() {
        addEvent("Added", "Question", "topics/" + request.params.topicId + "/files/" + request.params.fileId + "/questions/" + question._id, request.params.topicId);
        return response.send(question);
      }, function(error) {
        return response.send.apply(response, error);
      }).done();
    });
    app["delete"]('/topics/:topicId/files/:fileId/questions/:questionId', authenticated, function(request, response) {
      return findQuestion(request, request.params).then(function(_arg) {
        var file, question, topic;

        topic = _arg[0], file = _arg[1], question = _arg[2];
        file.questions.pull(question);
        return response.send(file);
      }, function(error) {
        return response.send.apply(response, error);
      }).done();
    });
    app.post('/topics/:topicId/files/:fileId/questions/:questionId', authenticated, function(request, response) {
      return findQuestion(request, request.params).then(function(_arg) {
        var file, question, topic;

        topic = _arg[0], file = _arg[1], question = _arg[2];
        question.text = request.body.text;
        question.modifiedQuestionTime = new Date();
        return Q.ninvoke(topic, 'save').then(function() {
          addEvent("Modified", "Question", "topics/" + request.params.topicId + "/files/" + request.params.fileId + "/questions/" + question._id, request.params.topicId);
          return response.send(question);
        }, function(error) {
          return response.send(error);
        }).done();
      }).done();
    });
    findQuestion = function(request, _arg) {
      var fileId, questionId, topicId;

      topicId = _arg.topicId, fileId = _arg.fileId, questionId = _arg.questionId;
      return findFile(request, {
        topicId: topicId,
        fileId: fileId
      }).then(function(_arg1) {
        var file, question, topic;

        topic = _arg1[0], file = _arg1[1];
        question = file.questions.id(questionId);
        return [topic, file, question];
      });
    };
    app.get('/topics/:topicId/files/:fileId/questions', authenticated, function(request, response) {
      return findQuestion(request, request.params).then(function(_arg) {
        var file, question, topic;

        topic = _arg[0], file = _arg[1], question = _arg[2];
        return response.send(file.questions);
      }, function(error) {
        return response.send.apply(response, error);
      }).done();
    });
    app.get('/topics/:topicId/files/:fileId/questions/:questionId', authenticated, function(request, response) {
      return findQuestion(request, request.params).then(function(_arg) {
        var file, question, topic;

        topic = _arg[0], file = _arg[1], question = _arg[2];
        return populateOwner(Question, question).then(function(question) {
          return response.send(question);
        });
      }, function(error) {
        return response.send.apply(response, error);
      }).done();
    });
    app.post('/topics/:topicId/files/:fileId/questions/:questionId/answers', authenticated, function(request, response) {
      return findQuestion(request, request.params).then(function(_arg) {
        var answer, file, question, topic;

        topic = _arg[0], file = _arg[1], question = _arg[2];
        answer = new Answer({
          owner: request.body.owner,
          rank: request.body.rank,
          text: request.body.text
        });
        question.answers.addToSet(answer);
        return Q.ninvoke(topic, 'save').then(function() {
          addEvent("Added", "Answer", "topics/" + topic._id + "/files/" + file._id + "/questions/" + question._id + "/answers/" + answer._id, request.params.topicId);
          return response.send(answer);
        });
      }, function(error) {
        return response.send.apply(response, error);
      }).done();
    });
    app.post('/topics/:topicId/files/:fileId/questions/:questionId/answers/:answerId', authenticated, function(request, response) {
      return findAnswer(request, request.params).then(function(_arg) {
        var answer, file, question, topic;

        topic = _arg[0], file = _arg[1], question = _arg[2], answer = _arg[3];
        answer.text = request.body.text;
        question.modifiedTime = new Date();
        return Q.ninvoke(topic, 'save').then(function() {
          addEvent("Modified", "Answer", "topics/" + topic._id + "/files/" + file._id + "/questions/" + question._id + "/answers/" + answer._id, request.params.topicId);
          return response.send(answer);
        }, function(error) {
          return response.send(error);
        }).done();
      }).done();
    });
    findAnswer = function(request, _arg) {
      var answerId, fileId, questionId, topicId;

      topicId = _arg.topicId, fileId = _arg.fileId, questionId = _arg.questionId, answerId = _arg.answerId;
      return findQuestion(request, {
        topicId: topicId,
        fileId: fileId,
        questionId: questionId
      }).then(function(_arg1) {
        var answer, file, question, topic;

        topic = _arg1[0], file = _arg1[1], question = _arg1[2];
        answer = question.answers.id(answerId);
        return [topic, file, question, answer];
      });
    };
    app.get('/topics/:topicId/files/:fileId/questions/:questionId/answers', authenticated, function(request, response) {
      return findAnswer(request, request.params).then(function(_arg) {
        var answer, file, question, topic;

        topic = _arg[0], file = _arg[1], question = _arg[2], answer = _arg[3];
        return response.send(question.answers);
      }, function(error) {
        return response.send.apply(response, error);
      }).done();
    });
    app.get('/topics/:topicId/files/:fileId/questions/:questionId/answers/:answerId', authenticated, function(request, response) {
      return findAnswer(request, request.params).then(function(_arg) {
        var answer, file, question, topic;

        topic = _arg[0], file = _arg[1], question = _arg[2], answer = _arg[3];
        return populateOwner(Answer, answer).then(function(answer) {
          return response.send(answer);
        });
      }, function(error) {
        return response.send.apply(response, error);
      }).done();
    });
    app.post('/topics/:topicId/files/:fileId/questions/:questionId/comments', authenticated, function(request, response) {
      var comment;

      comment = new CommentQ({
        owner: request.body.owner,
        text: request.body.text
      });
      return findQuestion(request, request.params).then(function(_arg) {
        var file, question, topic;

        topic = _arg[0], file = _arg[1], question = _arg[2];
        question.comments.addToSet(comment);
        return Q.ninvoke(topic, 'save');
      }).then(function() {
        addEvent("Added", "CommentQ", "topics/" + request.params.topicId + "/files/" + request.params.fileId + "/questions/" + request.params.questionId + "/comments/" + comment._id, request.params.topicId);
        return response.send(comment);
      }, function(error) {
        return response.send(error);
      }).done();
    });
    app.post('/topics/:topicId/files/:fileId/questions/:questionId/comments/:commentId', authenticated, function(request, response) {
      return findCommentQ(request, request.params).then(function(_arg) {
        var comment, file, question, topic;

        topic = _arg[0], file = _arg[1], question = _arg[2], comment = _arg[3];
        comment.text = request.body.text;
        question.modifiedTime = new Date();
        return Q.ninvoke(topic, 'save').then(function() {
          addEvent("Modified", "CommentQ", "topics/" + request.params.topicId + "/files/" + request.params.fileId + "/questions/" + request.params.questionId + "/comments/" + comment._id, request.params.topicId);
          return response.send(comment);
        }, function(error) {
          return response.send(error);
        }).done();
      }).done();
    });
    findCommentQ = function(request, _arg) {
      var commentId, fileId, questionId, topicId;

      topicId = _arg.topicId, fileId = _arg.fileId, questionId = _arg.questionId, commentId = _arg.commentId;
      return findQuestion(request, {
        topicId: topicId,
        fileId: fileId,
        questionId: questionId
      }).then(function(_arg1) {
        var comment, file, question, topic;

        topic = _arg1[0], file = _arg1[1], question = _arg1[2];
        comment = question.comments.id(commentId);
        return [topic, file, question, comment];
      });
    };
    app.get('/topics/:topicId/files/:fileId/questions/:questionId/comments', authenticated, function(request, response) {
      return findCommentQ(request, request.params).then(function(_arg) {
        var comment, file, question, topic;

        topic = _arg[0], file = _arg[1], question = _arg[2], comment = _arg[3];
        return response.send(question.comments);
      }, function(error) {
        return response.send.apply(response, error);
      }).done();
    });
    app.get('/topics/:topicId/files/:fileId/questions/:questionId/comments/:commentId', authenticated, function(request, response) {
      return findCommentQ(request, request.params).then(function(_arg) {
        var comment, file, question, topic;

        topic = _arg[0], file = _arg[1], question = _arg[2], comment = _arg[3];
        return populateOwner(CommentQ, comment).then(function(comment) {
          return response.send(comment);
        });
      }, function(error) {
        return response.send.apply(response, error);
      }).done();
    });
    app.post('/topics/:topicId/files/:fileId/questions/:questionId/answers/:answerId/comments', authenticated, function(request, response) {
      var comment;

      comment = new CommentA({
        owner: request.body.owner,
        text: request.body.text
      });
      return findAnswer(request, request.params).then(function(_arg) {
        var answer, file, question, topic;

        topic = _arg[0], file = _arg[1], question = _arg[2], answer = _arg[3];
        answer.comments.addToSet(comment);
        return Q.ninvoke(topic, 'save');
      }).then(function() {
        addEvent("Added", "CommentA", "topics/" + request.params.topicId + "/files/" + request.params.fileId + "/questions/" + request.params.questionId + "/answers/" + request.params.answerId + "/comments/" + comment._id, request.params.topicId);
        return response.send(comment);
      }, function(error) {
        return response.send.apply(response, error);
      }).done();
    });
    app.post('/topics/:topicId/files/:fileId/questions/:questionId/answers/:answerId/comments/:commentId', authenticated, function(request, response) {
      return findCommentA(request, request.params).then(function(_arg) {
        var answer, comment, file, question, topic;

        topic = _arg[0], file = _arg[1], question = _arg[2], answer = _arg[3], comment = _arg[4];
        comment.text = request.body.text;
        question.modifiedTime = new Date();
        return Q.ninvoke(topic, 'save').then(function() {
          addEvent("Modified", "CommentA", "topics/" + request.params.topicId + "/files/" + request.params.fileId + "/questions/" + request.params.questionId + "/answers/" + request.params.answerId + "/comments/" + comment._id, request.params.topicId);
          return response.send(comment);
        }, function(error) {
          return response.send(error);
        }).done();
      }).done();
    });
    populateOwner = function(model, type) {
      return Q.ninvoke(model, 'populate', type, {
        path: 'owner',
        select: '_id name'
      });
    };
    findCommentA = function(request, _arg) {
      var answerId, commentId, fileId, questionId, topicId;

      topicId = _arg.topicId, fileId = _arg.fileId, questionId = _arg.questionId, answerId = _arg.answerId, commentId = _arg.commentId;
      return findAnswer(request, {
        topicId: topicId,
        fileId: fileId,
        questionId: questionId,
        answerId: answerId
      }).then(function(_arg1) {
        var answer, comment, file, question, topic;

        topic = _arg1[0], file = _arg1[1], question = _arg1[2], answer = _arg1[3];
        comment = answer.comments.id(commentId);
        return [topic, file, question, answer, comment];
      });
    };
    app.get('/topics/:topicId/files/:fileId/questions/:questionId/answers/:answerId/comments', authenticated, function(request, response) {
      return findCommentA(request, request.params).then(function(_arg) {
        var answer, comment, file, question, topic;

        topic = _arg[0], file = _arg[1], question = _arg[2], answer = _arg[3], comment = _arg[4];
        return response.send(answer.comments);
      }, function(error) {
        return response.send.apply(response, error);
      }).done();
    });
    app.get('/topics/:topicId/files/:fileId/questions/:questionId/answers/:answerId/comments/:commentId', authenticated, function(request, response) {
      return findCommentA(request, request.params).then(function(_arg) {
        var answer, comment, file, question, topic;

        topic = _arg[0], file = _arg[1], question = _arg[2], answer = _arg[3], comment = _arg[4];
        return populateOwner(CommentA, comment).then(function(comment) {
          return response.send(comment);
        });
      }, function(error) {
        return response.send.apply(response, error);
      }).done();
    });
    app.get('/feeds/:user', authenticated, function(request, response) {
      return Q.ninvoke(User.findById(request.params.user).select('topics.code'), 'exec').then(function(_arg) {
        var code, topicCodes, topics;

        topics = _arg.topics;
        topicCodes = (function() {
          var _i, _len, _results;

          _results = [];
          for (_i = 0, _len = topics.length; _i < _len; _i++) {
            code = topics[_i].code;
            _results.push(code);
          }
          return _results;
        })();
        return Q.ninvoke(Question.find({}).populate({
          path: 'file',
          match: {
            topicCode: {
              $in: topicCodes
            }
          }
        }).sort('-modifiedTime'), 'exec').then(function(questions) {
          var q, _i, _len, _results;

          _results = [];
          for (_i = 0, _len = questions.length; _i < _len; _i++) {
            q = questions[_i];
            if (q.file != null) {
              _results.push(q);
            }
          }
          return _results;
        });
      }).then(function(questions) {
        return response.send(questions);
      }).done();
    });
    getAnswer = function(request, requestParams) {
      return findAnswer(request, request.params).then(function(_arg) {
        var answer, file, question, topic;

        topic = _arg[0], file = _arg[1], question = _arg[2], answer = _arg[3];
        return answer;
      });
    };
    app.post('/topics/:topicId/files/:fileId/questions/:questionId/answers/:answerId/voteUp/:username', authenticated, function(request, response) {
      return findAnswer(request, request.params).then(function(_arg) {
        var answer, file, question, topic;

        topic = _arg[0], file = _arg[1], question = _arg[2], answer = _arg[3];
        answer.votesFor.addToSet(request.params.username);
        return Q.ninvoke(topic, 'save');
      }).then(function() {
        return response.send("voted for");
      }, function(error) {
        return response.send.apply(response, error);
      }).done();
    });
    app.get('/topics/:topicId/files/:fileId/questions/:questionId/answers/:answerId/voteUp', authenticated, function(request, response) {
      return getAnswer(request, request.params).then(function(answer) {
        return response.send(answer.votesFor);
      });
    });
    return app.post('/topics/:topicId/files/:fileId/questions/:questionId/answers/:answerId/voteDown/:username', authenticated, function(request, response) {
      return findAnswer(request, request.params).then(function(_arg) {
        var answer, file, question, topic;

        topic = _arg[0], file = _arg[1], question = _arg[2], answer = _arg[3];
        answer.votesFor.pull(request.params.username);
        return Q.ninvoke(topic, 'save');
      }).then(function() {
        return response.send("voted against");
      }, function(error) {
        return response.send.apply(response, error);
      }).done();
    });
  };

}).call(this);
